id = "c3-zed"
name = "C3"
version = "0.0.1"
schema_version = 1
authors = ["Aiden Olsen <oslenaiden33@gmail.com>"]
description = "This extension bring basic c3 language support to zed. NOTE: This extenstion supports up to c3 version 0.6.1."
repository = "https://github.com/AineeJames/c3-zed"

[grammars.c3]
repository = "https://github.com/c3lang/tree-sitter-c3"
commit = "dd571e8a8ed4da58f5189e54f6dd0accf1daf388"
